name: portfolio cd


on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY : ${{ secrets.SSH_KEY_ENCODED }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          cd code-runner && \
          zip deployment.zip -r . && \
          echo ${SSH_PRIVATE_KEY} | base64 -d > sshkey && \
          scp -i sshkey deployment.zip ubuntu@${REMOTE_HOST}:/home/ubuntu/deployment.zip
