name: portfolio cd


on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY : ${{ secrets.SSH_KEY_ENCODED }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        zip deployment.zip -r . -x \*.git\* && \
        echo ${SSH_PRIVATE_KEY} | base64 -d > sshkey && \
        scp -i sshkey deployment.zip azureuser@${REMOTE_HOST}:/home/azureuser/Portfolio.zip
