name: Node.js CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Build Code
        run: npm run build --if-present

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          TARGET: '/home/azureuser/Portfolio'
          SOURCE: '/'
          ARGS: '--delete'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_NAME }}
          REMOTE_USER: azureuser